### ISSUE TITLE
Visualization of similarity graph

### ISSUE THREAD

**Issue by stronglily** [divamgupta/deep_clustering_kingdra#3]
Thank you for such an outstanding job！I have a question, what tool you used to draw the Figure 3 in your paper?

**Comment by divamgupta** [comment]
NetworkX

**Comment by stronglily** [comment]
Thank you for your reply！ @divamgupta

**Comment by stronglily** [comment]
Is it convenient for you to open code this part of drawing this figure? I'm very interested in your work and try to do the same work, but met with difficulty.

**Comment by stronglily** [comment]
Could you share the code that drew Figure 3? Please~ @divamgupta

**Comment by divamgupta** [comment]
Hi, so sorry I don't have that code anymore. Here are a few tips you can use to plot that figure:

1) Rather than plotting all the edges, you can plot a random subset of the edges
2) FIx the positions of the nodes across all iterations. 
3) Use spring_layout to compute the positions of the nodes. 

If you still face difficulties then I can look into your code and help you.

**Comment by stronglily** [comment]
Thank you so much, I'll try again with your tips. Best wishes!
